version: "3.8"

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./snippets:/etc/nginx/snippets
      - ../certs:/etc/nginx/certs
    networks:
      - saebasol

networks:
  saebasol:
    external: true
