version: "3.8"

services:
  mongodb:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: heliotrope
      MONGO_INITDB_ROOT_PASSWORD: heliotrope
    networks:
      - saebasol

networks:
  saebasol:
    external: true
